services:
  database:
    image: postgres
    container_name: database
    restart: unless-stopped
    environment:
      POSTGRES_USER: grade-class
      POSTGRES_PASSWORD: password
      POSTGRES_DB: grade-class
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  api:
    container_name: api-grades
    image: "node"
    user: "node"
    working_dir: /home/node/app
    ports:
      - '3000:3000'
    volumes:
      - ./backend/:/home/node/app
    depends_on:
      - database
    command: bash -c "npm install && npm run dev"

  # php-apache:
  #     container_name: php-apache
  #     build:
  #       context: ./php
  #     ports:
  #       - '8080:80'
  #     volumes:
  #       - ./src:/var/www/laravel_docker
  #       - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
  #     depends_on:
  #       - database
  #
