GET http://localhost:3000/api/grades/byid/1/23274013-2

GET http://localhost:3000/api/students/

GET http://localhost:3000/api/exams/byid/2/34859243-3

GET http://localhost:3000/api/subjects/1

GET http://localhost:3000/api/teachers/fdflsdkjfa

POST http://localhost:3000/api/createtables

POST http://localhost:3000/api/exams
        Accept: application/json,
        Content-Type: application/json
{
    "rut_student":"34859243-3",
    "id_subject":"1",
    "grade":"20",
    "exam":"true",
}
