GET http://localhost:3000/api/grades/byrut/5430991-1

GET http://localhost:3000/api/grades/byid/1

GET http://localhost:3000/fdslakjfdlskjfdsa

GET http://localhost:3000/api/subjects/1

GET http://localhost:3000/api/teachers/fdflsdkjfa

POST http://localhost:3000/api/createtables

POST http://localhost:3000/api/grades
Content-type: application/json

{
    "id":"1",
    "rut":"5430991-1",
    "grade":"99"
}
